### ISSUE TITLE
Add imports to init, to incorporate autocompletion of many Engines

### ISSUE THREAD

**Issue by 1D0BE** [MiniXC/simple-back#1]
In order to give autocompleters (e.g. IntelliSense) the possibility to autocomplete the classes defined by the package without problems, the following import should be added to `__init__.py`:

```
from .backtester import Backtester
from .price_providers import DailyPriceProvider, YahooFinanceProvider


__all__ = [
    "Backtester",
    "DailyPriceProvider",
    "YahooFinanceProvider"
]
```

**Comment by MiniXC** [comment]
fixed in c748117cfd5d08ca687f20eb3cd989f6bac83699, thanks for reporting
