### ISSUE TITLE
Segmentation fault while running example code in python3.6

### ISSUE THREAD

**Issue by fightthepower** [MiniXC/simple-back#16]
I am getting segmentation fault error while running example code in python3.6

```
from simple_back.backtester import BacktesterBuilder

builder = (
   BacktesterBuilder()
   .name('JNUG 20-Day Crossover')
   .balance(10_000)
   .calendar('NYSE')
   .compare(['JNUG']) # strategies to compare with
   .live_progress() # show a progress bar using tqdm
   .live_plot() # we assume we are running this in a Jupyter Notebook
)

bt = builder.build()
for day, event, b in bt['2019-1-1':'2020-1-1']:
    pass

```

This returns 

```
RuntimeError: main thread is not in main loop

>>> Segmentation fault
```

**Comment by MiniXC** [comment]
I think I came across this during development at some point, hope I can reproduce it.

**Comment by MiniXC** [comment]
It would be possible to simply switch to blocking plotting in terminal - this slows down the backtester significantly though. Would pair it with a warning about performance.

**Comment by fightthepower** [comment]
No I am not using a notebook and removing `live_plot` solved the problem
