### ISSUE TITLE
document matplotlib requirement for live plotting

### ISSUE THREAD

**Issue by natemoser** [MiniXC/simple-back#18]
My first run of a notebook got me 
```
[...]simple_back\backtester.py:1517: UserWarning: matplotlib not installed, setting live plotting to false
```

A simple 
```
pip install matplotlib
```
gets you over that bump, but since live plotting is one of the nice features of this backtester, it might be nice to mention that in the README.md or intro docs, especially if there's a minimum version needed. (I'm assuming that since there's a test for being able to successfully import matplotlib.pyplot that you want to keep the ability to deploy this w/o matplotlib rather than just add it to the requirements).

**Comment by MiniXC** [comment]
Added a note to the docs in 957e5b4 - I was also thinking of adding matplotlib as a requirement and optionally disabling it by installing with
``pip install simple_back[noplot]``, as most people will probably use this in Jupyter Notebooks, what do you think of this idea?

**Comment by natemoser** [comment]
Doc note looks good, and I agree the `[noplot]` modifier would be the right direction (if someone wants to run this as part of an automated pipeline, then a little extra and documented config is fine IMO).
